/**
 * This namespace wraps up the functionality for building the URLs used across pricing.
 *
 * @namespace urlBuilder
 * @urlBuilder The object to append all functionality to.
 * @undefined This parameter prevents undefined from being redefined by other JavaScript code.
 */
(function( urlBuilder, undefined ) {

    /**
     * Initialize this class by building the URLs.
     * @public
     */
    urlBuilder.initialize = function() {
        buildUrls();
    };

    // TODO: List each of the URLs here and what they are used for.
    /**
     * Build the URLs.
     *
     * Data Retrieval:
     *  - PRODUCT_PRICES            - Retrieves the ItemDTOs used to populate the Pricing Summary and Details tables.
     *  - PRODUCT_PRICE_SUMMARY     - Retrieves the totals displayed in the Right Pane's Pricing Summary.
     *  - PRODUCT_COST_CHARGES      - Used to populate the cost table.
     *  - PRODUCT_USAGE_CHARGE      - Used to populate the usage table.
     *  - PRODUCT_REVENUE           - Used to populate the revenue table.
     *
     * Pricing Actions:
     *  - BID_MANAGERS              - ?
     *  - UNLOCK_PRICE_LINES        - Called by a Bid Manager to unlock the Price Lines after they have been locked by a Discount Request.
     *  - REQUEST_DISCOUNT_APPROVAL - ?
     *
     * BCM
     *  - BCM_URL                   - Generates and returns a new BCM sheet for the price lines.
     *  - BCM_NOT_NEW_EXPORT_URL    - Returns a BCM sheet that was generated by a previous call to BCM_URL.
     *
     * @private
     */
    function buildUrls() {

        // Extract the values required to build the end point URLs from the Free Marker template.
        var CUSTOMER_ID                 = $('#customerId').html();
        var CONTRACT_ID                 = $('#contractId').html();
        var PROJECT_ID                  = $('#projectId').html();
        var QUOTE_OPTION_ID             = $('#quoteOptionId').html();
        var REQUEST_DISCOUNT_ACTION_URL = $('#requestDiscountActionUrl').html();
        var BCM_URL                     = $('#importBCMActionUrl').html();

        var SQE_BASE_URL                = "/rsqe/customers/" + CUSTOMER_ID +
                                          "/contracts/"      + CONTRACT_ID +
                                          "/projects/"       + PROJECT_ID  +
                                          "/quote-options/"  + QUOTE_OPTION_ID;

        var PRICING_ACTIONS_BASE_URL = REQUEST_DISCOUNT_ACTION_URL;

        // Data Retrieval:
        urlBuilder.PRODUCT_PRICES            = SQE_BASE_URL + "/product-prices";
        urlBuilder.PRODUCT_PRICE_SUMMARY     = SQE_BASE_URL + "/product-price-summary";
        urlBuilder.PRODUCT_COST_CHARGES      = SQE_BASE_URL + "/product-cost-charges";
        urlBuilder.PRODUCT_USAGE_CHARGE      = SQE_BASE_URL + "/product-usage-charges";
        urlBuilder.PRODUCT_REVENUE           = SQE_BASE_URL + "/revenue";

        // Pricing Actions:
        urlBuilder.BID_MANAGERS              = PRICING_ACTIONS_BASE_URL + '/bid-managers';
        urlBuilder.UNLOCK_PRICE_LINES        = PRICING_ACTIONS_BASE_URL + '/unlock-price-lines';
        urlBuilder.REQUEST_DISCOUNT_APPROVAL = PRICING_ACTIONS_BASE_URL + '/request-discount-approval';

        // BCM:
        urlBuilder.BCM_URL                   = BCM_URL;
        urlBuilder.BCM_NOT_NEW_EXPORT_URL    = BCM_URL + '?newBcmExportVersion=no';

    }

}(
    // Immediately invoke this namespace.
    rsqe.urlBuilder = rsqe.urlBuilder || {}
));