CREATE SYNONYM EXP__IPSDK__USER_ROLES FOR RSQE_EXP_DBLINK.EXP__IPSDK__USER_ROLES@DBLINK_CQM_EXP
//

create synonym EXP__IPSDK__USERCONFIGURATION for rsqe_exp_dblink.EXP__IPSDK__USERCONFIGURATION@DBLINK_CQM_EXP
//

create synonym POM__CFG__USER_DETAILS for rsqe_exp_dblink.POM__CFG__USER_DETAILS@dblink_cqm_exp
//
