CREATE TABLE QUOTE_MASTER
(
    QUOTE_MASTER_ID           VARCHAR2(50) NOT NULL,
    QUOTE_ID                  VARCHAR2(100),
    QUOTE_NAME                VARCHAR2(100),
    QUOTE_OPTION_ID           VARCHAR2(100) NOT NULL,
    QUOTE_OPTION_NAME         VARCHAR2(100) NOT NULL,
    CUSTOMER_ID               VARCHAR2(50) NOT NULL,
    CUSTOMER_NAME             VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM             VARCHAR2(10) NOT NULL,
    CUSTOMER_MORE_INFO        VARCHAR2(200),
    SALES_CHANNEL_ID          VARCHAR2(50) NOT NULL,
    SALES_CHANNEL_NAME        VARCHAR2(100) NOT NULL,
    SALES_CHANNEL_TYPE        VARCHAR2(50) NOT NULL,
    CURRENCY                  VARCHAR2(100) NOT NULL,
    TIER                      VARCHAR2(50),
    CONTRACT_VALUE            VARCHAR2(20),
    CONTRACT_LENGTH           VARCHAR2(20) NOT NULL,
    ALTERNATE_CONTACT         VARCHAR2(100),
    WIN_CHANCE                VARCHAR2(10),
    CREATED_BY_EIN            VARCHAR2(25) NOT NULL,
    CREATED_BY_EMAIL          VARCHAR2(25) NOT NULL,
    CREATED_USER              VARCHAR2(25) NOT NULL,
    CREATED_DATE              TIMESTAMP(6) NOT NULL,
    MODIFIED_USER             VARCHAR2(25) NOT NULL,
    MODIFIED_DATE             TIMESTAMP(6) NOT NULL
)//

ALTER TABLE QUOTE_MASTER ADD CONSTRAINT PK_QUOTE_MASTER_ID PRIMARY KEY (QUOTE_MASTER_ID)//
ALTER TABLE QUOTE_MASTER ADD CONSTRAINT UK_QUOTE_OPTION_ID UNIQUE (QUOTE_OPTION_ID)//

CREATE TABLE REQUEST_MASTER
(
    REQUEST_ID                  VARCHAR2(100) NOT NULL,
    REQUEST_NAME                VARCHAR2(100) NOT NULL,
    QUOTE_MASTER_ID             VARCHAR2(50) NOT NULL,
    PRODUCT_CATEGORY_CODE       VARCHAR2(50) NOT NULL,
    PRODUCT_CATEGORY_NAME       VARCHAR2(100) NOT NULL,
    TEMPLATE_CODE               VARCHAR2(50) NOT NULL,
    TEMPLATE_NAME               VARCHAR2(100) NOT NULL,
    TEMPLATE_VERSION            VARCHAR2(50) NOT NULL,
    WORK_FLOW_TYPE              VARCHAR2(100) NOT NULL,
    EVALUATED_MODE              VARCHAR2(100),
    OUTPUT_DESC			        VARCHAR2(200),
    RESPONSE_TYPE               VARCHAR2(50) NOT NULL,
    CONFIGURATION_TYPE          VARCHAR2(300) NOT NULL,
    IS_REUSABLE			        CHAR(1) NOT NULL,  --Y OR N
    SPECIAL_BID_CATEGORY        VARCHAR2(300) NOT NULL,
    US_TAX_CATEGORY             VARCHAR2(300) NOT NULL,
    DATA_BUILD_REQUIRED         CHAR(1) NOT NULL,  --Y OR N
    DATA_BUILD_COMPLETED        CHAR(1) NOT NULL,  --Y OR N
    EXPECTED_RESPONSE_TIME      VARCHAR2(20) NOT NULL,
    STATE                       VARCHAR2(20) NOT NULL,
    PUBLIC_URL                  VARCHAR2(500),
    ATTACHMENTS                 VARCHAR2(500),
    BILL_DESCRIPTION            VARCHAR2(200),
    DETAILED_RESPONSE           CLOB,
    ALERT_EMAIL_ADDRESS         VARCHAR2(100),
    IS_ALERT_ON_APPROVAL_ONLY   CHAR(1) NOT NULL,  --Y OR N
    ALERT_MESSAGE			    VARCHAR2(200),
    IS_VPN_DATA_REQD		    CHAR(1) NOT NULL,  --Y OR N
    IS_COTC_VISIBLE             CHAR(1) NOT NULL,  --Y OR N
    COMMENTS                    CLOB,
    CREATED_USER                VARCHAR2(25),
    CREATED_DATE                TIMESTAMP(6),
    MODIFIED_USER               VARCHAR2(25),
    MODIFIED_DATE               TIMESTAMP(6)
)//

ALTER TABLE REQUEST_MASTER ADD CONSTRAINT PK_REQUEST_ID PRIMARY KEY (REQUEST_ID)//
ALTER TABLE REQUEST_MASTER ADD CONSTRAINT FK_QUOTE_MASTER_ID FOREIGN KEY (QUOTE_MASTER_ID) REFERENCES QUOTE_MASTER (QUOTE_MASTER_ID)//
CREATE SEQUENCE REQUEST_MASTER_SEQUENCE MINVALUE 100 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100000 CACHE 20 NOORDER NOCYCLE//

CREATE TABLE REQUEST_SITE
(
    REQUEST_SITE_ID                 VARCHAR2(50) NOT NULL,
    REQUEST_ID                      VARCHAR2(100) NOT NULL,
    SITE_ID                         VARCHAR2(60) NOT NULL,
    SITE_NAME			            VARCHAR2(100),
    COUNTRY_NAME	                VARCHAR2(100),
    COUNTRY_ISO_ALPHA2_CODE		    VARCHAR2(100) NOT NULL,
    CREATED_USER                    VARCHAR2(25),
    CREATED_DATE                    TIMESTAMP(6),
    MODIFIED_USER                   VARCHAR2(25),
    MODIFIED_DATE                   TIMESTAMP(6)
)//

ALTER TABLE REQUEST_SITE ADD CONSTRAINT PK_REQUEST_SITE_ID PRIMARY KEY (REQUEST_SITE_ID)//
ALTER TABLE REQUEST_SITE ADD CONSTRAINT FK_REQUEST_ID_RS FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//

CREATE TABLE REQUEST_ATTRIBUTE
(
    REQUEST_ATTRIBUTE_ID            VARCHAR2(50) NOT NULL,
    REQUEST_ID                      VARCHAR2(100) NOT NULL,
    REQUEST_SITE_ID                 VARCHAR2(60),
    SQE_UNIQUE_ID                  VARCHAR2(100),
    ATTRIBUTE_NAME                  VARCHAR2(60) NOT NULL,
    DEFAULT_VALUE			        VARCHAR2(100),
    ATTRIBUTE_VALUE_HEADER	        VARCHAR2(100),
    ATTRIBUTE_VALUE			        VARCHAR2(200) NOT NULL,
    ATTRIBUTE_VALUE_DISPLAY_NAME	VARCHAR2(200),
    ATTRIBUTE_VALUE_DISPLAY_INDEX	NUMBER,
    CONTROLLER_TYPE			        VARCHAR2(100),
    REQUIRED			            CHAR(1) NOT NULL,
    DATA_TYPE			            VARCHAR2(50),
    DISPLAY_NAME			        VARCHAR2(200),
    DISPLAY_INDEX			        NUMBER,
    TOOLTIP				            VARCHAR2(100),
    MINIMUM_LENGTH			        NUMBER,
    MAXIMUM_LENGTH			        NUMBER,
    MINIMUM_DATA_VALUE		        VARCHAR2(200),
    MAXIMUM_DATA_VALUE		        VARCHAR2(200),
    FREEDOM_TEXT_COLUMNS		    NUMBER,
    FREEDOM_TEXT_ROWS		        NUMBER,
    ATTRIBUTE_PLACEHOLDER		    VARCHAR2(20) NOT NULL,
    CREATED_USER                    VARCHAR2(25),
    CREATED_DATE                    TIMESTAMP(6),
    MODIFIED_USER                   VARCHAR2(25),
    MODIFIED_DATE                   TIMESTAMP(6)
)//

ALTER TABLE REQUEST_ATTRIBUTE ADD CONSTRAINT PK_REQUEST_ATTRIBUTE_ID PRIMARY KEY (REQUEST_ATTRIBUTE_ID)//
ALTER TABLE REQUEST_ATTRIBUTE ADD CONSTRAINT FK_REQUEST_ID_RA FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//
ALTER TABLE REQUEST_ATTRIBUTE ADD CONSTRAINT FK_REQUEST_SITE_ID_RA FOREIGN KEY (REQUEST_SITE_ID) REFERENCES REQUEST_SITE (REQUEST_SITE_ID)//

CREATE TABLE REQUEST_PRICE_GROUP
(
	REQUEST_PG_ID			        VARCHAR2(50) NOT NULL,
	REQUEST_SITE_ID                 VARCHAR2(60) NOT NULL,
	SQE_UNIQUE_ID                   VARCHAR2(100),
	PRICE_GROUP_TYPE		        VARCHAR2(15) NOT NULL,
	PRICE_GROUP_DESC		        VARCHAR2(200) NOT NULL,
	ONE_OFF_RECOMMENDED_RETAIL	    VARCHAR2(200),
	RECURRING_RECOMMENDED_RETAIL	VARCHAR2(200),
	NRC_PRICE_TO_PARTNER		    VARCHAR2(200),
	RC_PRICE_TO_PARTNER		        VARCHAR2(200),
	ONE_OFF_COST			        VARCHAR2(200),
	RECURRING_COST			        VARCHAR2(200),
	STATUS				            VARCHAR2(10) DEFAULT 'ACTIVE',
    CREATED_USER                    VARCHAR2(25),
    CREATED_DATE                    TIMESTAMP(6),
    MODIFIED_USER                   VARCHAR2(25),
    MODIFIED_DATE                   TIMESTAMP(6)
)//

ALTER TABLE REQUEST_PRICE_GROUP ADD CONSTRAINT REQUEST_PG_ID_PK PRIMARY KEY ( REQUEST_PG_ID )//
ALTER TABLE REQUEST_PRICE_GROUP ADD CONSTRAINT FK_REQUEST_SITE_ID_RPG FOREIGN KEY (REQUEST_SITE_ID) REFERENCES REQUEST_SITE (REQUEST_SITE_ID)//

CREATE TABLE REQUEST_EVALUATOR
(
    REQUEST_EVALUATOR_ID    VARCHAR2(50) NOT NULL,
    REQUEST_ID			    VARCHAR2(100) NOT NULL,
    EVALUATOR_GROUP_ID      VARCHAR2(50) NOT NULL,
    EVALUATOR_GROUP_NAME    VARCHAR2(100) NOT NULL,
    STATE                   VARCHAR2(100) NOT NULL,
    RESPONSE                VARCHAR2(100) DEFAULT 'None',
    COMMENTS                CLOB,
    DECISION                CLOB,
    ACCEPTED_BY             VARCHAR2(50),
    ACCEPTED_BY_NAME        VARCHAR2(50),
    ACCEPTED_DATE           DATE,
    CLOSED_BY               VARCHAR2(50),
    CLOSED_BY_NAME          VARCHAR2(50),
    CLOSED_DATE             DATE,
    CURRENCY                VARCHAR2(100),
    STATUS                  VARCHAR2(10) DEFAULT 'ACTIVE',
    CREATED_USER            VARCHAR2(25),
    CREATED_USER_NAME       VARCHAR2(50),
    CREATED_DATE            TIMESTAMP(6),
    MODIFIED_USER           VARCHAR2(25),
    MODIFIED_USER_NAME      VARCHAR2(50),
    MODIFIED_DATE           TIMESTAMP(6)
)//

ALTER TABLE REQUEST_EVALUATOR ADD CONSTRAINT PK_REQUEST_EVALUATOR_ID PRIMARY KEY (REQUEST_EVALUATOR_ID)//
ALTER TABLE REQUEST_EVALUATOR ADD CONSTRAINT FK_REQUEST_ID_RG FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//

CREATE TABLE REQUEST_EVALUATOR_SITE
(
    REQUEST_EVALUATOR_SITE_ID       VARCHAR2(50) NOT NULL,
    REQUEST_EVALUATOR_ID            VARCHAR2(50) NOT NULL,
    SITE_ID                         VARCHAR2(60) NOT NULL,
    SITE_NAME			            VARCHAR2(100),
    COUNTRY_NAME	                VARCHAR2(100),
    COUNTRY_ISO_ALPHA2_CODE		    VARCHAR2(100) NOT NULL,
    CREATED_USER                    VARCHAR2(25),
    CREATED_DATE                    TIMESTAMP(6),
    MODIFIED_USER                   VARCHAR2(25),
    MODIFIED_DATE                   TIMESTAMP(6)
)//

ALTER TABLE REQUEST_EVALUATOR_SITE ADD CONSTRAINT PK_REQUEST_EVALUATOR_SITE_ID PRIMARY KEY (REQUEST_EVALUATOR_SITE_ID)//
ALTER TABLE REQUEST_EVALUATOR_SITE ADD CONSTRAINT FK_REQUEST_EVALUATOR_ID_RES FOREIGN KEY (REQUEST_EVALUATOR_ID) REFERENCES REQUEST_EVALUATOR (REQUEST_EVALUATOR_ID)//

CREATE TABLE REQUEST_EVALUATOR_PRICE_GROUP
(
	REQUEST_EVALUATOR_PG_ID			VARCHAR2(50) NOT NULL,
	REQUEST_EVALUATOR_SITE_ID       VARCHAR2(60) NOT NULL,
	PRICE_GROUP_TYPE		        VARCHAR2(15) NOT NULL,
	PRICE_GROUP_DESC		        VARCHAR2(200) NOT NULL,
	ONE_OFF_RECOMMENDED_RETAIL	    VARCHAR2(200),
	RECURRING_RECOMMENDED_RETAIL	VARCHAR2(200),
	NRC_PRICE_TO_PARTNER		    VARCHAR2(200),
	RC_PRICE_TO_PARTNER		        VARCHAR2(200),
	ONE_OFF_COST			        VARCHAR2(200),
	RECURRING_COST			        VARCHAR2(200),
	STATUS				            VARCHAR2(10) DEFAULT 'ACTIVE',
    CREATED_USER                    VARCHAR2(25),
    CREATED_DATE                    TIMESTAMP(6),
    MODIFIED_USER                   VARCHAR2(25),
    MODIFIED_DATE                   TIMESTAMP(6)
)//

ALTER TABLE REQUEST_EVALUATOR_PRICE_GROUP ADD CONSTRAINT REQUEST_EPG_ID_PK PRIMARY KEY ( REQUEST_EVALUATOR_PG_ID )//
ALTER TABLE REQUEST_EVALUATOR_PRICE_GROUP ADD CONSTRAINT FK_REQUEST_EVAL_SITE_ID_REPG FOREIGN KEY (REQUEST_EVALUATOR_SITE_ID) REFERENCES REQUEST_EVALUATOR_SITE (REQUEST_EVALUATOR_SITE_ID)//

CREATE TABLE REQUEST_HISTORY
(
    REQUEST_HISTORY_ID      VARCHAR2(50) NOT NULL,
    REQUEST_ID		        VARCHAR2(100) NOT NULL,
    STATE_TO                VARCHAR2(20) NOT NULL,
    CREATED_USER            VARCHAR2(25),
    CREATED_USER_NAME       VARCHAR2(100),
    CREATED_DATE            TIMESTAMP(6)
)//

ALTER TABLE REQUEST_HISTORY ADD CONSTRAINT PK_REQ_HIST_ID PRIMARY KEY (REQUEST_HISTORY_ID)//
ALTER TABLE REQUEST_HISTORY ADD CONSTRAINT FK_REQUEST_ID_RH FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//

CREATE TABLE REQUEST_WHO_HAS_SEEN
(
    REQUEST_WHO_HAS_SEEN_ID     VARCHAR2(50) NOT NULL,
    REQUEST_ID			        VARCHAR2(100) NOT NULL,
    STATE                       VARCHAR2(10) DEFAULT 'ACTIVE',
    CREATED_USER                VARCHAR2(25),
    CREATED_USER_NAME           VARCHAR2(100),
    CREATED_DATE                TIMESTAMP(6)
)//

ALTER TABLE REQUEST_WHO_HAS_SEEN ADD CONSTRAINT PK_REQUEST_WHO_HAS_SEEN_ID PRIMARY KEY (REQUEST_WHO_HAS_SEEN_ID)//
ALTER TABLE REQUEST_WHO_HAS_SEEN ADD CONSTRAINT FK_REQUEST_ID_RWHS FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//

CREATE TABLE CUSTOMER_ONE_TIME_CHARGE
(
    CUSTOMER_ID               VARCHAR2(50) NOT NULL ,
    TEMPLATE_ID               VARCHAR2(50) NOT NULL,
    COTC_FLAG                 CHAR(1) NOT NULL,
    CREATED_USER              VARCHAR2(25),
    CREATED_DATE              TIMESTAMP(6),
    MODIFIED_USER             VARCHAR2(25),
    MODIFIED_DATE             TIMESTAMP(6)
)//

CREATE TABLE USER_GROUP
(
    USER_ID                     VARCHAR2(50) NOT NULL,
    EVALUATOR_GROUP_ID          VARCHAR2(50) NOT NULL,
    PRODUCT_CATEGORY_CODE       VARCHAR2(50) NOT NULL,
    CREATED_USER                VARCHAR2(25),
    CREATED_DATE                TIMESTAMP(6)
)//

ALTER TABLE USER_GROUP ADD CONSTRAINT PK_GRP_USER_PROD_ID PRIMARY KEY ( USER_ID, EVALUATOR_GROUP_ID, PRODUCT_CATEGORY_CODE)//

CREATE TABLE USER_PRODUCT
(
    USER_ID                   VARCHAR2(50) NOT NULL,
    PRODUCT_CATEGORY_CODE     VARCHAR2(50) NOT NULL,
    CREATED_USER              VARCHAR2(25),
    CREATED_DATE              TIMESTAMP(6)
)//

ALTER TABLE USER_PRODUCT add constraint PK_USER_PROD_ID PRIMARY KEY (USER_ID, PRODUCT_CATEGORY_CODE)//

CREATE TABLE REQUEST_RESPONSE_LOGS
(
    LOG_ID                      VARCHAR2(50) NOT NULL,
    REQUEST_ID			        VARCHAR2(100) NOT NULL,
    REQUEST_NAME                VARCHAR2(100),
    QUOTE_OPTION_ID             VARCHAR2(50) NOT NULL,
    QUOTE_OPTION_NAME           VARCHAR2(100),
    CUSTOMER_ID                 VARCHAR2(50),
    CUSTOMER_NAME               VARCHAR2(50),
    REQUEST                     CLOB,
    RESPONSE                    CLOB,
    ORIGINATING_SYSTEM          VARCHAR2(50),
    SERVICE_CALL                VARCHAR2(100),
    CREATED_USER                VARCHAR2(25),
    CREATED_DATE                TIMESTAMP(6)
)//

ALTER TABLE REQUEST_RESPONSE_LOGS ADD CONSTRAINT PK_REQ_RES_LOGS_ID PRIMARY KEY (LOG_ID)//
ALTER TABLE REQUEST_RESPONSE_LOGS ADD CONSTRAINT FK_REQUEST_ID_RRL FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_MASTER (REQUEST_ID)//