CREATE TABLE APPLICATION_PROPERTY_STORE
(
    PROPERTY_NAME VARCHAR2(100 CHAR) NOT NULL,
    PROPERTY_VALUE VARCHAR2(256 CHAR) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT APPLICATION_PROPERTY_STORE PRIMARY KEY (PROPERTY_NAME) ENABLE
)
//