CREATE TABLE QUOTE_OPTION_APP_PROP_STORE
(
    QUOTE_OPTION_ID VARCHAR2(50) NOT NULL,
    PROPERTY_NAME VARCHAR2(100 CHAR) NOT NULL,
    PROPERTY_VALUE VARCHAR2(256 CHAR) NOT NULL,
    COMMENTS VARCHAR2(256 CHAR) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT QO_APP_PROPERTY_STORE PRIMARY KEY (QUOTE_OPTION_ID, PROPERTY_NAME) ENABLE
)
//