Insert into USER_MASTER (USER_ID,USER_NAME,FIRST_NAME,LAST_NAME,JOB_TITLE,EMAIL_ID,PHONE_NUMBER,ROLE_TYPE_ID,ACTIVE,LAST_LOGIN,LOCATION,MOBILE,CREATED_DATE,CREATED_USER,MODIFIED_DATE,MODIFIED_USER) values ('608026723','Ullas Ramakrishnan','Ullas','Ramakrishnan','','ullas.ramakrishnan@bt.com','9988776655',1,'Y',null,null,null,SYSDATE,'Initial Load',SYSDATE,'Initial Load')//

Insert into ROLE_MASTER (ROLE_ID,ROLE_NAME,ROLE_TYPE_ID,ROLE_GROUP_ID,ACTIVE,CREATED_DATE,CREATED_USER,MODIFIED_DATE,MODIFIED_USER) values (18,'EPM Super User',1,1,'Y',SYSDATE,'Initial Load',SYSDATE,'Initial Load')//
Insert into ROLE_MASTER (ROLE_ID,ROLE_NAME,ROLE_TYPE_ID,ROLE_GROUP_ID,ACTIVE,CREATED_DATE,CREATED_USER,MODIFIED_DATE,MODIFIED_USER) values (19,'CSPPMF Super User',1,1,'Y',SYSDATE,'Initial Load',SYSDATE,'Initial Load')//

Insert into USER_ROLE (USER_ID,ROLE_ID,CREATED_DATE,CREATED_USER,DEFAULT_ROLE) values ('608143048',4,SYSDATE,'Initial Load','Y')//
Insert into USER_ROLE (USER_ID,ROLE_ID,CREATED_DATE,CREATED_USER,DEFAULT_ROLE) values ('608143048',18,SYSDATE,'Initial Load','Y')//
Insert into USER_ROLE (USER_ID,ROLE_ID,CREATED_DATE,CREATED_USER,DEFAULT_ROLE) values ('608143048',19,SYSDATE,'Initial Load','Y')//
Insert into USER_ROLE (USER_ID,ROLE_ID,CREATED_DATE,CREATED_USER,DEFAULT_ROLE) values ('608026723',7,SYSDATE,'Initial Load','Y')//
Insert into USER_ROLE (USER_ID,ROLE_ID,CREATED_DATE,CREATED_USER,DEFAULT_ROLE) values ('608026723',4,SYSDATE,'Initial Load','Y')//
