package com.bt.rsqe.utils.countries;

import java.util.List;

import static com.google.common.collect.Lists.*;

public class EnumCountryProvider implements CountryProvider {
    static enum CountryData {
        AF("AFG","AFGHANISTAN","Afghanistan",false,false),
        AX("ALA","AALAND ISLANDS","Aland Islands",false,true),
        DZ("DZA","ALGERIA","Algeria",false,true),
        AL("ALB","ALBANIA","Albania",false,false),
        AS("ASM","AMERICAN SAMOA","American Samoa",false,true),
        AD("AND","ANDORRA","Andorra",false,true),
        AO("AGO","ANGOLA","Angola",false,false),
        AI("AIA","ANGUILLA","Anguilla",false,true),
        AQ("ATA","ANTARCTICA","Antarctica",false,true),
        AG("ATG","ANTIGUA AND BARBUDA","Antigua and Barbuda",false,false),
        AR("ARG","ARGENTINA","Argentina",false,true),
        AM("ARM","ARMENIA","Armenia",false,false),
        AW("ABW","ARUBA","Aruba",false,false),
        AU("AUS","AUSTRALIA","Australia",true,true),
        AT("AUT","AUSTRIA","Austria",false,true),
        AZ("AZE","AZERBAIJAN","Azerbaijan",false,true),
        BS("BHS","BAHAMAS","Bahamas",false,false),
        BH("BHR","BAHRAIN","Bahrain",false,true),
        BD("BGD","BANGLADESH","Bangladesh",false,true),
        BB("BRB","BARBADOS","Barbados",false,true),
        BY("BLR","BELARUS","Belarus",false,true),
        BE("BEL","BELGIUM","Belgium",false,true),
        BZ("BLZ","BELIZE","Belize",false,false),
        BJ("BEN","BENIN","Benin",false,false),
        BM("BMU","BERMUDA","Bermuda",false,true),
        BT("BTN","BHUTAN","Bhutan",false,true),
        BO("BOL","BOLIVIA","Bolivia",false,false),
        BA("BIH","BOSNIA AND HERZEGOVINA","Bosnia and Herzegovina",false,true),
        BW("BWA","BOTSWANA","Botswana",false,false),
        BV("BVT","BOUVET ISLAND","Bouvet Island",false,true),
        BR("BRA","BRAZIL","Brazil",true,true),
        IO("IOT","BRITISH INDIAN OCEAN TERRITORY","British Indian Ocean Territory",false,false),
        BN("BRN","BRUNEI DARUSSALAM","Brunei Darussalam",false,true),
        BG("BGR","BULGARIA","Bulgaria",false,true),
        BF("BFA","BURKINA FASO","Burkina Faso",false,false),
        BI("BDI","BURUNDI","Burundi",false,false),
        KH("KHM","CAMBODIA","Cambodia",false,true),
        CM("CMR","CAMEROON","Cameroon",false,false),
        CA("CAN","CANADA","Canada",true,true),
        CV("CPV","CAPE VERDE","Cape Verde",false,true),
        KY("CYM","CAYMAN ISLANDS","Cayman Islands",false,true),
        CF("CAF","CENTRAL AFRICAN REPUBLIC","Central African Republic",false,false),
        TD("TCD","CHAD","Chad",false,false),
        CL("CHL","CHILE","Chile",false,true),
        CN("CHN","CHINA","China",true,true),
        CX("CXR","CHRISTMAS ISLAND","Christmas Island",false,true),
        CC("CCK","COCOS (KEELING) ISLANDS","Cocos (Keeling) Islands",false,true),
        CO("COL","COLOMBIA","Colombia",false,true),
        KM("COM","COMOROS","Comoros",false,false),
        CG("COG","CONGO","Congo",false,true),
        CD("COD","CONGO, THE DEMOCRATIC REPUBLIC OF THE","Congo, The Democratic Republic of The",false,false),
        CK("COK","COOK ISLANDS","Cook Islands",false,false),
        CR("CRI","COSTA RICA","Costa Rica",false,true),
        HR("HRV","CROATIA","Croatia",false,true),
        CU("CUB","CUBA","Cuba",false,true),
        CY("CYP","CYPRUS","Cyprus",false,true),
        CZ("CZE","CZECH REPUBLIC","Czech Republic",false,true),
        DK("DNK","DENMARK","Denmark",false,true),
        DJ("DJI","DJIBOUTI","Djibouti",false,false),
        DM("DMA","DOMINICA","Dominica",false,false),
        DO("DOM","DOMINICAN REPUBLIC","Dominican Republic",false,true),
        EC("ECU","ECUADOR","Ecuador",false,true),
        EG("EGY","EGYPT","Egypt",false,true),
        SV("SLV","EL SALVADOR","El Salvador",false,true),
        GQ("GNQ","EQUATORIAL GUINEA","Equatorial Guinea",false,false),
        ER("ERI","ERITREA","Eritrea",false,false),
        EE("EST","ESTONIA","Estonia",false,true),
        ET("ETH","ETHIOPIA","Ethiopia",false,true),
        FK("FLK","FALKLAND ISLANDS (MALVINAS)","Falkland Islands (Malvinas)",false,true),
        FO("FRO","FAROE ISLANDS","Faroe Islands",false,true),
        FJ("FJI","FIJI","Fiji",false,false),
        FI("FIN","FINLAND","Finland",false,true),
        FR("FRA","FRANCE","France",false,true),
        GF("GUF","FRENCH GUIANA","French Guiana",false,true),
        PF("PYF","FRENCH POLYNESIA","French Polynesia",false,true),
        TF("ATF","FRENCH SOUTHERN TERRITORIES","French Southern Territories",false,true),
        GA("GAB","GABON","Gabon",false,false),
        GM("GMB","GAMBIA","Gambia",false,false),
        GE("GEO","GEORGIA","Georgia",false,true),
        DE("DEU","GERMANY","Germany",false,true),
        GH("GHA","GHANA","Ghana",false,false),
        GI("GIB","GIBRALTAR","Gibraltar",false,true),
        GR("GRC","GREECE","Greece",false,true),
        GL("GRL","GREENLAND","Greenland",false,true),
        GD("GRD","GRENADA","Grenada",false,false),
        GP("GLP","GUADELOUPE","Guadeloupe",false,true),
        GU("GUM","GUAM","Guam",false,true),
        GT("GTM","GUATEMALA","Guatemala",false,true),
        GG("GGY","GUERNSEY","Guernsey",false,true),
        GN("GIN","GUINEA","Guinea",false,true),
        GW("GNB","GUINEA-BISAU","Guinea-Bissau",false,true),
        GY("GUY","GUYANA","Guyana",false,false),
        HT("HTI","HAITI","Haiti",false,true),
        HM("HMD","HEARD AND MC DONALD ISLANDS","Heard Island and McDonald Islands",false,false),
        VA("VAT","HOLY SEE (VATICAN CITY STATE)","Holy See (Vatican City State)",false,true),
        HN("HND","HONDURAS","Honduras",false,true),
        HK("HKG","HONG KONG","Hong Kong",false,false),
        HU("HUN","HUNGARY","Hungary",false,true),
        IS("ISL","ICELAND","Iceland",false,true),
        ID("IDN","INDONESIA","Indonesia",false,true),
        IR("IRN","IRAN, ISLAMIC REPUBLIC OF","Iran, Islamic Republic of",false,true),
        IQ("IRQ","IRAQ","Iraq",false,true),
        IE("IRL","IRELAND","Ireland",false,false),
        IM("IMN","ISLE OF MAN","Isle of Man",false,true),
        IL("ISR","ISRAEL","Israel",false,true),
        IT("ITA","ITALY","Italy",false,true),
        JM("JAM","JAMAICA","Jamaica",false,true),
        JP("JPN","JAPAN","Japan",true,true),
        JE("JEY","JERSEY","Jersey",false,true),
        JO("JOR","JORDAN","Jordan",false,true),
        KZ("KAZ","KAZAKHSTAN","Kazakhstan",false,true),
        KE("KEN","KENYA","Kenya",false,true),
        KI("KIR","KIRIBATI","Kiribati",false,false),
        KP("PRK","KOREA, DEMOCRATIC PEOPLES REPUBLIC OF","Korea, Democratic People's Republic of",false,true),
        KR("KOR","KOREA, REPUBLIC OF", "Korea, Republic of",false,true),
        KW("KWT","KUWAIT","Kuwait",false,true),
        KG("KGZ","KYRGYZSTAN","Kyrgyzstan",false,true),
        LA("LAO","LAO PEOPLES DEMOCRATIC REPUBLIC","Lao People's Democratic Republic",false,true),
        LV("LVA","LATVIA","Latvia",false,true),
        LB("LBN","LEBANON","Lebanon",false,true),
        LS("LSO","LESOTHO","Lesotho",false,true),
        LR("LBR","LIBERIA","Liberia",false,true),
        LY("LBY","LIBYA","Libya",false,false),
        LI("LIE","LIECHTENSTEIN","Liechtenstein",false,true),
        LT("LTU","LITHUANIA","Lithuania",false,true),
        LU("LUX","LUXEMBOURG","Luxembourg",false,true),
        MO("MAC","MACAU","Macao",false,false),
        MK("MKD","MACEDONIA","Macedonia",false,true),
        MG("MDG","MADAGASCAR","Madagascar",false,true),
        MW("MWI","MALAWI","Malawi",false,false),
        MY("MYS","MALAYSIA","Malaysia",false,true),
        MV("MDV","MALDIVES","Maldives",false,true),
        ML("MLI","MALI","Mali",false,false),
        MT("MLT","MALTA","Malta",false,true),
        MH("MHL","MARSHALL ISLANDS","Marshall Islands",false,true),
        MQ("MTQ","MARTINIQUE","Martinique",false,true),
        MR("MRT","MAURITANIA","Mauritania",false,false),
        MU("MUS","MAURITIUS","Mauritius",false,true),
        YT("MYT","MAYOTTE","Mayotte",false,true),
        MX("MEX","MEXICO","Mexico",false,true),
        FM("FSM","MICRONESIA, FEDERATED STATES OF","Micronesia, Federated States of",false,true),
        MD("MDA","MOLDOVA, REPUBLIC OF","Moldova, Republic of",false,true),
        MC("MCO","MONACO","Monaco",false,true),
        MN("MNG","MONGOLIA","Mongolia",false,true),
        MS("MSR","MONTSERRAT","Montserrat",false,false),
        MA("MAR","MOROCCO","Morocco",false,true),
        MZ("MOZ","MOZAMBIQUE","Mozambique",false,true),
        MM("MMR","MYANMAR","Myanmar",false,true),
        NA("NAM","NAMIBIA","Namibia",false,false),
        NR("NRU","NAURU","Nauru",false,false),
        NP("NPL","NEPAL","Nepal",false,true),
        NL("NLD","NETHERLANDS","Netherlands",false,true),
        AN("ANT","NETHERLANDS ANTILLES","Netherlands Antilles",false,false),
        NC("NCL","NEW CALEDONIA","New Caledonia",false,true),
        NZ("NZL","NEW ZEALAND","New Zealand",false,true),
        NI("NIC","NICARAGUA","Nicaragua",false,true),
        NE("NER","NIGER","Niger",false,true),
        NG("NGA","NIGERIA","Nigeria",false,true),
        NU("NIU","NIUE","Niue",false,false),
        NF("NFK","NORFOLK ISLAND","Norfolk Island",false,true),
        MP("MNP","NORTHERN MARIANA ISLANDS","Northern Mariana Islands",false,true),
        NO("NOR","NORWAY","Norway",false,true),
        OM("OMN","OMAN","Oman",false,true),
        PK("PAK","PAKISTAN","Pakistan",false,true),
        PW("PLW","PALAU","Palau",false,true),
        PS("PSE","UNKNOWN","Palestinian Territory, Occupied",false,true),
        PA("PAN","PANAMA","Panama",false,true),
        PG("PNG","PAPUA NEW GUINEA","Papua New Guinea",false,true),
        PY("PRY","PARAGUAY","Paraguay",false,true),
        PE("PER","PERU","Peru",false,true),
        PH("PHL","PHILIPPINES","Philippines",false,true),
        PN("PCN","PITCAIRN","Pitcairn",false,false),
        PL("POL","POLAND","Poland",false,true),
        PT("PRT","PORTUGAL","Portugal",false,true),
        PR("PRI","PUERTO RICO","Puerto Rico",false,true),
        QA("QAT","QATAR","Qatar",false,false),
        RE("REU","REUNION","Reunion",false,true),
        RO("ROU","ROMANIA","Romania",false,true),
        RU("RUS","RUSSIAN FEDERATION","Russian Federation",false,true),
        RW("RWA","RWANDA","Rwanda",false,false),
        SH("SHN","SAINT HELENA","Saint Helena",false,true),
        KN("KNA","SAINT KITTS AND NEVIS","Saint Kitts and Nevis",false,false),
        LC("LCA","SAINT LUCIA","Saint Lucia",false,false),
        PM("SPM","SAINT PIERRE AND MIQUELON","Saint Pierre and Miquelon",false,true),
        VC("VCT","SAINT VINCENT AND THE GRENADINES","Saint Vincent and The Grenadines",false,true),
        WS("WSM","SAMOA","Samoa",false,false),
        SM("SMR","SAN MARINO","San Marino",false,true),
        ST("STP","SAO TOME AND PRINCIPE","Sao Tome and Principe",false,false),
        SA("SAU","SAUDI ARABIA","Saudi Arabia",false,true),
        SN("SEN","SENEGAL","Senegal",false,true),
        SC("SYC","SEYCHELLES","Seychelles",false,false),
        SL("SLE","SIERRA LEONE","Sierra Leone",false,false),
        SG("SGP","SINGAPORE","Singapore",false,true),
        SK("SVK","SLOVAKIA","Slovakia",false,true),
        SI("SVN","SLOVENIA","Slovenia",false,true),
        SB("SLB","SOLOMON ISLANDS","Solomon Islands",false,false),
        SO("SOM","SOMALIA","Somalia",false,true),
        ZA("ZAF","SOUTH AFRICA","South Africa",false,true),
        GS("SGS","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","South Georgia & South Sandwich Islands",false,false),
        ES("ESP","SPAIN","Spain",false,true),
        LK("LKA","SRI LANKA","Sri Lanka",false,true),
        SD("SDN","SUDAN","Sudan",false,true),
        SR("SUR","SURINAME","Suriname",false,false),
        SJ("SJM","SVALBARD AND JAN MAYEN ISLANDS","Svalbard and Jan Mayen",false,true),
        SZ("SWZ","SWAZILAND","Swaziland",false,true),
        SE("SWE","SWEDEN","Sweden",false,true),
        CH("CHE","SWITZERLAND","Switzerland",false,true),
        SY("SYR","SYRIAN ARAB REPUBLIC","Syrian Arab Republic",false,false),
        TW("TWN","TAIWAN, PROVINCE OF CHINA","Taiwan, Province of China",false,true),
        TJ("TJK","TAJIKISTAN","Tajikistan",false,true),
        TZ("TZA","TANZANIA, UNITED REPUBLIC OF","Tanzania, United Republic of",false,false),
        TH("THA","THAILAND","Thailand",false,true),
        TL("TLS","TIMOR-LESTE","Timor-Leste",false,true),
        TG("TGO","TOGO","Togo",false,false),
        TK("TKL","TOKELAU","Tokelau",false,false),
        TO("TON","TONGA","Tonga",false,false),
        TT("TTO","TRINIDAD AND TOBAGO","Trinidad and Tobago",false,false),
        TN("TUN","TUNISIA","Tunisia",false,true),
        TR("TUR","TURKEY","Turkey",false,true),
        TM("TKM","TURKMENISTAN","Turkmenistan",false,true),
        TC("TCA","TURKS AND CAICOS ISLANDS","Turks and Caicos Islands",false,true),
        TV("TUV","TUVALU","Tuvalu",false,false),
        UG("UGA","UGANDA","Uganda",false,false),
        UA("UKR","UKRAINE","Ukraine",false,true),
        AE("ARE","UNITED ARAB EMIRATES","United Arab Emirates",false,false),
        GB("GBR","UNITED KINGDOM","United Kingdom",false,true),
        UM("UMI","UNITED STATES MINOR OUTLYING ISLANDS","United States Minor Outlying Islands",false,true),
        UY("URY","URUGUAY","Uruguay",false,true),
        UZ("UZB","UZBEKISTAN","Uzbekistan",false,true),
        VU("VUT","VANUATU","Vanuatu",false,false),
        VE("VEN","VENEZUELA","Venezuela",false,true),
        VN("VNM","VIET NAM","Viet Nam",false,false),
        VG("VGB","VIRGIN ISLANDS, BRITISH","Virgin Islands, British",false,true),
        VI("VIR","VIRGIN ISLANDS, U.S.","Virgin Islands, U.S.",false,true),
        WF("WLF","WALLIS AND FUTUNA ISLANDS","Wallis and Futuna",false,true),
        EH("ESH","WESTERN SAHARA","Western Sahara",false,true),
        YE("YEM","YEMEN","Yemen",false,false),
        ZM("ZMB","ZAMBIA","Zambia",false,true),
        ZW("ZWE","ZIMBABWE","Zimbabwe",false,false),
        US("USA","UNITED STATES","United States",true,true),
        ME("MNE","MONTENEGRO","Montenegro",false,true),
        RS("SRB","SERBIA","Serbia",false,true),
        IN("IND","INDIA","India",true,true),
        CI("CIV","COTE DIVOIRE","Cote d'Ivoire",false,true),
        BQ("BES","BONAIRE, SINT EUSTATIUS AND SABA","Bonaire, Sint Eustatius And Saba",false,false),
        CW("CUW","CURACAO","Curacao",false,false),
        BL("BLM","SAINT BARTHELEMY","Saint Barthelemy",false,false),
        MF("MAF","SAINT MARTIN (FRENCH PART)","Saint Martin (French Part)",false,false),
        SX("SXM","SINT MAARTEN (DUTCH PART)","Sint Maarten (Dutch Part)",false,false);

        public final String alpha3;
        public final String expedioName;
        public final String displayName;
        public final boolean stateRequired;
        public final boolean zipRequired;

        CountryData(String alpha3, String expedioName, String displayName, boolean stateRequired, boolean zipRequired) {
            this.alpha3 = alpha3;
            this.expedioName = expedioName;
            this.displayName = displayName;
            this.stateRequired = stateRequired;
            this.zipRequired = zipRequired;
        }
    }

    @Override
    public Country[] loadCountries() {
        List<Country> countries = newArrayList();

        for(CountryData country : CountryData.values()) {
            countries.add(new Country(country.name(),
                                      country.alpha3,
                                      country.expedioName,
                                      country.displayName,
                                      country.stateRequired,
                                      country.zipRequired));
        }

        return countries.toArray(new Country[]{});
    }
}
