DECLARE tbl_exist INTEGER; BEGIN SELECT count(*) INTO tbl_exist FROM USER_TABLES WHERE table_name = 'APE_REQUEST'; IF tbl_exist = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE APE_REQUEST CASCADE CONSTRAINTS'; END IF; END;//
DECLARE tbl_exist INTEGER; BEGIN SELECT count(*) INTO tbl_exist FROM USER_TABLES WHERE table_name = 'APE_QREF_DETAIL'; IF tbl_exist = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE APE_QREF_DETAIL CASCADE CONSTRAINTS'; END IF; END;//

CREATE TABLE APE_REQUEST
(
    REQUEST_ID VARCHAR2(50 CHAR) NOT NULL ENABLE,
    UNIQUE_ID VARCHAR2(100 CHAR) NOT NULL ENABLE,
    CONSTRAINT APE_REQUEST_DETAIL_PK PRIMARY KEY (REQUEST_ID) ENABLE
)
//

CREATE TABLE APE_QREF_DETAIL
(
    REQUEST_ID VARCHAR2(50 CHAR) NOT NULL ENABLE,
    QREF_ID VARCHAR2(100 CHAR) NOT NULL ENABLE,
    ATTRIBUTE_NAME VARCHAR2(100 CHAR) NOT NULL ENABLE,
    ATTRIBUTE_VALUE VARCHAR2(100 CHAR),
    CONSTRAINT APE_QREF_DETAIL_PK PRIMARY KEY (REQUEST_ID, QREF_ID, ATTRIBUTE_NAME) ENABLE,
    CONSTRAINT APE_QREF_DETAIL_FK FOREIGN KEY (REQUEST_ID) REFERENCES APE_REQUEST (REQUEST_ID) ENABLE
)//

CREATE INDEX APE_QREF_IX on APE_QREF_DETAIL(REQUEST_ID)
//