CREATE TABLE APE_QREF_ERROR
(
    ERROR_ID VARCHAR2(50 CHAR) NOT NULL ENABLE,
    QREF_ID VARCHAR2(100 CHAR) NOT NULL ENABLE,
    ERROR_CODE VARCHAR2(100 CHAR),
    ERROR_MSG VARCHAR2(300 CHAR) NOT NULL ENABLE,
    CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE,
    CONSTRAINT APE_QREF_ERROR_PK PRIMARY KEY (ERROR_ID) ENABLE
)
//