CREATE TABLE ACCESS_STAFF_COMMENT
(
    STAFF_COMMENT_ID VARCHAR2(50 CHAR) NOT NULL ENABLE,
    QREF_ID VARCHAR2(100 CHAR) NOT NULL ENABLE,
    STAFF_COMMENT VARCHAR2(300 CHAR) NOT NULL ENABLE,
    STAFF_EMAIL VARCHAR2(300 CHAR),
    STAFF_NAME  VARCHAR2(300 CHAR),
    CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE,
    CONSTRAINT ACCESS_STAFF_COMMENT_PK PRIMARY KEY (STAFF_COMMENT_ID) ENABLE
)
//