CREATE TABLE APE_REQUEST_DETAIL
(
    REQUEST_ID VARCHAR2(50 CHAR) NOT NULL ENABLE,
    ATTRIBUTE_NAME VARCHAR2(100 CHAR) NOT NULL ENABLE,
    ATTRIBUTE_VALUE VARCHAR2(100 CHAR),
    CONSTRAINT "APE_REQUEST_DETAIL_UK1" UNIQUE ("REQUEST_ID", "ATTRIBUTE_NAME") ENABLE
)
//