CREATE INDEX QREF_DETAIL_QREF_ID_IDX ON APE_QREF_DETAIL (QREF_ID) //
CREATE INDEX STAFF_COMMENTS_QREF_ID_IDX ON ACCESS_STAFF_COMMENT (QREF_ID) //
CREATE INDEX QREF_ERROR_QREF_IDX ON APE_QREF_ERROR (QREF_ID) //
CREATE INDEX APE_REQUEST_UNIQUE_ID_IDX ON APE_REQUEST (UNIQUE_ID) //
