DECLARE tbl_exist INTEGER; BEGIN SELECT COUNT (*) INTO tbl_exist FROM USER_TABLES WHERE table_name = 'DSL_EFM_SUPPORTED_COUNTRIES'; IF tbl_exist > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE DSL_EFM_SUPPORTED_COUNTRIES CASCADE CONSTRAINTS'; END IF; END;//

CREATE TABLE DSL_EFM_SUPPORTED_COUNTRIES
(
   ISO_CODE                 CHAR (2),
   COUNTRY                  VARCHAR2 (255) NOT NULL,
   DSL_EFM_SUPPORTED        CHAR (3),
   UPDATED_ON               TIMESTAMP(6)
)
//

ALTER TABLE DSL_EFM_SUPPORTED_COUNTRIES ADD CONSTRAINT ISO_CODE_PK PRIMARY KEY(ISO_CODE)
//

INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Afghanistan','AF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Åland Islands','AX', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Albania','AL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Algeria','DZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('American Samoa','AS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Andorra','AD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Angola','AO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Anguilla','AI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Antarctica','AQ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Antigua and Barbuda','AG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Argentina','AR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Armenia','AM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Aruba','AW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Australia','AU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Austria','AT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Azerbaijan','AZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bahamas','BS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bahrain','BH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bangladesh','BD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Barbados','BB', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Belarus','BY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Belgium','BE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Belize','BZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Benin','BJ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bermuda','BM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bhutan','BT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bolivia, Plurinational State of','BO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bonaire, Sint Eustatius and Saba','BQ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bosnia and Herzegovina','BA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Botswana','BW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bouvet Island','BV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Brazil','BR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('British Indian Ocean Territory','IO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Brunei Darussalam','BN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Bulgaria','BG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Burkina Faso','BF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Burundi','BI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cambodia','KH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cameroon','CM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Canada','CA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cape Verde','CV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cayman Islands','KY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Central African Republic','CF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Chad','TD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Chile','CL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('China','CN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Christmas Island','CX', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cocos (Keeling) Islands','CC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Colombia','CO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Comoros','KM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Congo','CG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Congo,the Democratic Republic of the','CD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cook Islands','CK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Costa Rica','CR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Côte dIvoire','CI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Croatia','HR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cuba','CU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Curaçao','CW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Cyprus','CY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Czech Republic','CZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Denmark','DK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Djibouti','DJ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Dominica','DM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Dominican Republic','DO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Ecuador','EC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Egypt','EG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('El Salvador','SV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Equatorial Guinea','GQ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Eritrea','ER', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Estonia','EE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Ethiopia','ET', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Falkland Islands (Malvinas)','FK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Faroe Islands','FO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Fiji','FJ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Finland','FI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('France','FR', 'Yes', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('French Guiana','GF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('French Polynesia','PF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('French Southern Territories','TF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Gabon','GA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Gambia','GM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Georgia','GE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Germany','DE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Ghana','GH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Gibraltar','GI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Greece','GR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Greenland','GL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Grenada','GD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guadeloupe','GP', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guam','GU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guatemala','GT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guernsey','GG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guinea','GN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guinea-Bissau','GW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Guyana','GY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Haiti','HT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Heard Island and McDonald Islands','HM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Holy See (Vatican City State)','VA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Honduras','HN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Hong Kong','HK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Hungary','HU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Iceland','IS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('India','IN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Indonesia','ID', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Iran, Islamic Republic of','IR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Iraq','IQ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Ireland','IE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Isle of Man','IM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Israel','IL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Italy','IT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Jamaica','JM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Japan','JP', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Jersey','JE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Jordan','JO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Kazakhstan','KZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Kenya','KE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Kiribati','KI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Korea,Democratic Peoples Republic of','KP', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Korea,Republic of','KR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Kuwait','KW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Kyrgyzstan','KG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Lao Peoples Democratic Republic','LA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Latvia','LV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Lebanon','LB', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Lesotho','LS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Liberia','LR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Libya','LY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Liechtenstein','LI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Lithuania','LT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Luxembourg','LU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Macao','MO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Macedonia, the Former Yugoslav Republic of','MK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Madagascar','MG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Malawi','MW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Malaysia','MY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Maldives','MV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mali','ML', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Malta','MT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Marshall Islands','MH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Martinique','MQ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mauritania','MR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mauritius','MU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mayotte','YT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mexico','MX', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Micronesia, Federated States of','FM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Moldova, Republic of','MD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Monaco','MC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mongolia','MN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Montenegro','ME', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Montserrat','MS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Morocco','MA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Mozambique','MZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Myanmar','MM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Namibia','NA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Nauru','NR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Nepal','NP', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Netherlands','NL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('New Caledonia','NC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('New Zealand','NZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Nicaragua','NI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Niger','NE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Nigeria','NG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Niue','NU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Norfolk Island','NF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Northern Mariana Islands','MP', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Norway','NO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Oman','OM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Pakistan','PK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Palau','PW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Palestine, State of','PS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Panama','PA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Papua New Guinea','PG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Paraguay','PY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Peru','PE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Philippines','PH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Pitcairn','PN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Poland','PL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Portugal','PT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Puerto Rico','PR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Qatar','QA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Réunion','RE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Romania','RO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Russian Federation','RU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Rwanda','RW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Barthélemy','BL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Kitts and Nevis','KN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Lucia','LC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Martin (French part)','MF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Pierre and Miquelon','PM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saint Vincent and the Grenadines','VC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Samoa','WS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('San Marino','SM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sao Tome and Principe','ST', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Saudi Arabia','SA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Senegal','SN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Serbia','RS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Seychelles','SC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sierra Leone','SL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Singapore','SG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sint Maarten (Dutch part)','SX', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Slovakia','SK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Slovenia','SI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Solomon Islands','SB', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Somalia','SO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('South Africa','ZA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('South Georgia and the South Sandwich Islands','GS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('South Sudan','SS', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Spain','ES', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sri Lanka','LK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sudan','SD', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Suriname','SR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Svalbard and Jan Mayen','SJ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Swaziland','SZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Sweden','SE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Switzerland','CH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Syrian Arab Republic','SY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Taiwan, Province of China','TW', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tajikistan','TJ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tanzania, United Republic of','TZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Thailand','TH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Timor-Leste','TL', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Togo','TG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tokelau','TK', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tonga','TO', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Trinidad and Tobago','TT', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tunisia','TN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Turkey','TR', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Turkmenistan','TM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Turks and Caicos Islands','TC', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Tuvalu','TV', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Uganda','UG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Ukraine','UA', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('United Arab Emirates','AE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('United Kingdom','GB', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('United States','US', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('United States Minor Outlying Islands','UM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Uruguay','UY', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Uzbekistan','UZ', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Vanuatu','VU', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Venezuela, Bolivarian Republic of','VE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Viet Nam','VN', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Virgin Islands, British','VG', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Virgin Islands, U.S.','VI', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Wallis and Futuna','WF', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Western Sahara','EH', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Yemen','YE', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Zambia','ZM', 'No', sysdate)
//
INSERT INTO DSL_EFM_SUPPORTED_COUNTRIES (COUNTRY, ISO_CODE, DSL_EFM_SUPPORTED, UPDATED_ON) VALUES ('Zimbabwe','ZW', 'No', sysdate)
//
