DECLARE tbl_exist INTEGER; BEGIN SELECT COUNT (*) INTO tbl_exist FROM USER_TABLES WHERE table_name = 'AVAILABILITY_REQUEST_QUEUE'; IF tbl_exist > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE AVAILABILITY_REQUEST_QUEUE CASCADE CONSTRAINTS'; EXECUTE IMMEDIATE 'DROP SEQUENCE ARQ_ID'; END IF; END;//

CREATE TABLE AVAILABILITY_REQUEST_QUEUE
(
   ARQ_ID                          NUMBER,
   CLIENT_REQUEST                  VARCHAR2 (255),
   APE_REQUEST                     VARCHAR2 (255),
   SITE_ID                         NUMBER (10),
   TASK                            VARCHAR2 (100),
   STATUS                          VARCHAR2 (20),
   CREATED_ON                      TIMESTAMP(6)
)
//

ALTER TABLE AVAILABILITY_REQUEST_QUEUE ADD CONSTRAINT ARQ_PK PRIMARY KEY(ARQ_ID)
//

CREATE SEQUENCE ARQ_ID
   START WITH 1
   MAXVALUE 999999999999999999999999999
   MINVALUE 1
   NOCYCLE
   CACHE 100
   NOORDER
//